import Link from 'next/link'
import data from '../data'
import styles from '../styles/Home.module.css'
import Cards from '../components/Cards'

<<<<<<< HEAD
const teams = data

export default function Home(){
  return(
    
      <h1>Landing</h1>
      
    {/*<Link href='/imperial'><h3>Imperial</h3></Link>
      <Link href='/wnw'><h3>W N W</h3></Link>*/}
=======
import data from './api/data.json'


export default function Home() {

  const dados = data
  const logo = dados?.teamlogo

  
  return (
    <div className={styles.container}>
      <Head>
        <title>CS GO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bem vindo ao HLTV - CS GO
        </h1>

        <p className={styles.description}>
          Noticias diárias e ranks atualizados semanalmente{' '}
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Teams &rarr;</h2>
            <p>All the best teams on the scennary.</p>
            <p>{data.teamLogo}</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Players &rarr;</h2>
            <p>All the best players of the world.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Tournaments &rarr;</h2>
            <p>Schedule of tournaments including Major.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Rankings &rarr;</h2>
            <p>
              Rankins updated every week by the player and teams.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
>>>>>>> d6252bdeab3c51058e93ad95b24ecc092a4440ae
    </div>
  )
}